apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  ap-default.conf: |
    upstream app_backend_com {
        zone app_backend_group 64k;
        server 127.0.0.1:80;
    }

    server {
        listen 8080;
        server_name perpod.example.com;
        proxy_http_version 1.1;

        app_protect_enable on;
        app_protect_security_log_enable on;
        app_protect_security_log "/etc/nginx/custom_log_format.json" syslog:server=127.0.0.1:514;

        location / {
            client_max_body_size 0;
            app_protect_policy_file "/etc/nginx/custom_policy.json";
            default_type text/html;
            # set your backend here
            proxy_pass http://app_backend_com;
            proxy_set_header Host $host;
        }

        location /api {
            api write=on;
            # directives limiting access to the API
        }

        location = /dashboard.html {
            root   /usr/share/nginx/html;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perpod-nap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perpod-nap
  template:
    metadata:
      labels:
        app: perpod-nap
    spec:
      containers:
      - name: tea
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
      - name: perpod-nap
        image: nginx-plus-nap:latest 
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d/
            readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: ap-default.conf
              path: ap-default.conf
              mode: 0644
---
apiVersion: v1
kind: Service
metadata:
  name: perpod-nap-svc
  labels:
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: perpod-nap
